sudo: required

notifications:
  email: false

language: python
python:
  - 3.6

services:
  - docker

install:
  - pip install flake8 pydocstyle schema_salad
  - pip install -r requirements.txt
  - git clone https://github.com/common-workflow-language/common-workflow-language.git
  - schema-salad-tool --codegen python common-workflow-language/v1.0/CommonWorkflowLanguage.yml > cwl_parser.py

script:
  - make lint
  # -Wi is to prevent warnings in the external libraries
  - make test

after_success:
  - ./deploy.sh
